### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by cadorn** [1999/sklad#1]
Are you planning on publishing sklad to NPM? Would be useful.

This is a great library. Why do you think it has not deserved the attention it deserves?

**Comment by quarterto** [comment]
Please reconsider this. It's very common to install clientside modules with npm and bundle them with Browserify or Webpack. You already have a valid package.json; all you need to do is run `npm publish`.

**Comment by 1999** [comment]
@quarterto yep, you're right. I'll do this today

**Comment by 1999** [comment]
Finally: https://www.npmjs.com/package/sklad

**Comment by quarterto** [comment]
Fantastic, thanks.
